services:
    pj-neblina-laravel-hub:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
            - ./docker/server_start.sh:/usr/local/bin/server_start.sh
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./storage:/var/www/storage
            - ./vendor:/var/www/vendor
        ports:
            - "8081:8081"
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            APP_URL: ${APP_URL}
            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            TZ: America/Sao_Paulo
        command: ["/bin/sh", "-c", "/bin/bash /usr/local/bin/server_start.sh"]
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: 2G

networks:
    app-network:
        name: "app-network"
        driver: bridge
